export const GET_ITEMS_START = 'GET_ITEMS_START';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL';

export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const ADD_ITEM_START = 'ADD_ITEM_START';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';

export const LOAD_MORE_TRANSACTIONS_START = 'LOAD_MORE_TRANSACTIONS_START';
export const LOAD_MORE_TRANSACTIONS_SUCCESS = 'LOAD_MORE_TRANSACTIONS_SUCCESS';
export const LOAD_MORE_TRANSACTIONS_FAIL = 'LOAD_MORE_TRANSACTIONS_FAIL';

export const ADD_FILTER_INVENTORY = 'ADD_FILTER_INVENTORY';
export const CLEAR_FILTER_INVENTORY = 'CLEAR_FILTER_INVENTORY';

export const ADD_SORT = 'ADD_SORT';
export const CLEAR_SORT = 'CLEAR_SORT';
