export const GET_ITEMS_START_DASHBOARD = 'GET_ITEMS_START_DASHBOARD ';
export const GET_ITEMS_SUCCESS_DASHBOARD = 'GET_ITEMS_SUCCESS_DASHBOARD ';
export const GET_ITEMS_FAIL_DASHBOARD = 'GET_ITEMS_FAIL_DASHBOARD ';

export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const ADD_ITEM_START = 'ADD_ITEM_START';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';

export const LOAD_MORE_TRANSACTIONS_START = 'LOAD_MORE_TRANSACTIONS_START';
export const LOAD_MORE_TRANSACTIONS_SUCCESS = 'LOAD_MORE_TRANSACTIONS_SUCCESS';
export const LOAD_MORE_TRANSACTIONS_FAIL = 'LOAD_MORE_TRANSACTIONS_FAIL';

export const ADD_SORT_DASHBOARD = 'ADD_SORT_DASHBOARD';
export const CLEAR_SORT_DASHBOARD = 'CLEAR_SORT_DASHBOARD';
