export const GET_SALES_START = 'GET_SALES_START';
export const GET_SALES_SUCCESS = 'GET_SALES_SUCCESS';
export const GET_SALES_FAIL = 'GET_SALES_FAIL';

export const GET_PAYMENT_START = 'GET_PAYMENT_START';
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS';
export const GET_PAYMENT_FAIL = 'GET_PAYMENT_FAIL';

export const ADD_SALES_START = 'ADD_SALES_START';
export const ADD_SALES_SUCCESS = 'ADD_SALES_SUCCESS';
export const ADD_SALES_FAIL = 'ADD_SALES_FAIL';

export const ADD_FILTER_SALES = 'ADD_FILTER_SALES';
export const CLEAR_FILTER_SALES = 'CLEAR_FILTER_SALES';

export const ADD_DISCOUNT = 'ADD_DISCOUNT';
export const CLEAR_DISCOUNT = 'CLEAR_DISCOUNT';

export const ADD_SEARCH_SALES = 'ADD_SEARCH_SALES';
export const CLEAR_SEARCH_SALES = 'CLEAR_SEARCH_SALES';
