export const GET_ORDERS_START = 'GET_ORDERS_START';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';

export const GET_PAYMENT_START = 'GET_PAYMENT_START';
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS';
export const GET_PAYMENT_FAIL = 'GET_PAYMENT_FAIL';

export const ADD_ORDERS_START = 'ADD_ORDERS_START';
export const ADD_ORDERS_SUCCESS = 'ADD_ORDERS_SUCCESS';
export const ADD_ORDERS_FAIL = 'ADD_ORDERS_FAIL';

export const ADD_FILTER_ORDER = 'ADD_FILTER_ORDER';
export const CLEAR_FILTER_ORDER = 'CLEAR_FILTER_ORDER';
